version: '2'
services:
  web:
    build: ./conf/web/nginx
    env_file: ./conf/web/nginx/nginx.env
    ports:
        - "80:80"
    volumes:
        - ./conf/web/nginx/vhosts:/etc/nginx/conf.d/
        - ./web:/${WWW}

  php:
    image: php:7-fpm
    volumes:
        - ./web:/${WWW}

  mysql:
    image: percona
    env_file: ./conf/mysql/mysql.env
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
