version: '2'
services:
  web:
    build: ./conf/web/apache
    env_file: ./conf/web/apache/apache.env
    ports:
      - "80:80"
    volumes:
      - ./web:/${WWW}
      - ./conf/web/apache/vhosts:/etc/apache2/sites-enabled
    tty: true

  php:
    image: php:7-fpm
    volumes:
      - ./web:/${WWW}

  mysql:
    image: percona
    env_file: ./conf/mysql/mysql.env
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql

  node:
    image: node
    user: node
    expose:
      - "8081"
    tty: true
